theme: "jekyll-theme-minimal"
title: "Workshop Ciência de Dados"
description: Observatório Obstétrico Brasileiro
avatar: /docs/logo.png
params:
  social_image_path:    /docs/logo.png
  main:                 "https://getbootstrap.com"
  github_org:           "https://github.com/twbs"
  repo:                 "https://github.com/twbs/icons"
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com"
  blog:                 "https://blog.getbootstrap.com"
  expo:                 "https://expo.getbootstrap.com"
  themes:               "https://themes.getbootstrap.com"
  opencollective:       "https://opencollective.com/bootstrap"
  icons_figma:          "https://www.figma.com/community/file/1042482994486402696/Bootstrap-Icons"
github:
  is_project_page: false
